import React,{useEffect,useRef,useState}from'react';
import {io,Socket}from'socket.io-client';
import {MessageCircle,Send,Plus,RefreshCw,Headphones}from'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api/v1';
const SOCKET=(import.meta.env.VITE_SOCKET_URL||'http://localhost:5000');
interface Ticket{id:string;subject:string;status:string;priority:string;updated_at:string}
interface Msg{id:string;sender_user_id:string;sender_name:string;message_text:string;sent_at:string;is_internal_note:boolean}

export default function HelpDesk(){
 const token=localStorage.getItem('nersf_token')||'';const user=JSON.parse(localStorage.getItem('nersf_user')||'{}');
 const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [text,setText]=useState('');const [subject,setSubject]=useState('');const [creating,setCreating]=useState(false);const [msg,setMsg]=useState('');
 const socket=useRef<Socket|null>(null);const bottom=useRef<HTMLDivElement>(null);
 const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
 const load=async()=>{try{const r=await fetch(API+'/helpdesk/tickets/my',{headers});const d=await r.json();if(!r.ok)throw new Error(d.message);setTickets(d);}catch(e:any){setMsg(e.message||'Unable to load support tickets.');}};
 const open=async(t:Ticket)=>{setSelected(t);try{const r=await fetch(API+'/helpdesk/tickets/'+t.id+'/messages',{headers});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessages(d);}catch(e:any){setMsg(e.message||'Unable to load messages.');}};
 useEffect(()=>{load();socket.current=io(SOCKET,{auth:{token}});return()=>socket.current?.disconnect();},[]);
 useEffect(()=>{if(!selected||!socket.current)return;const room='ticket_'+selected.id;socket.current.emit('join_ticket',selected.id);const handler=(m:Msg)=>{if(!m.is_internal_note)setMessages(x=>[...x,m]);};socket.current.on('chat_message',handler);return()=>{socket.current?.off('chat_message',handler);};},[selected]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{const r=await fetch(API+'/helpdesk/tickets',{method:'POST',headers,body:JSON.stringify({subject})});const d=await r.json();if(!r.ok)throw new Error(d.message);setSubject('');setCreating(false);setMsg('Support ticket created. A support agent can now assist you.');load();}catch(e:any){setMsg(e.message||'Unable to create ticket.');}};
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!text.trim())return;const body={message:text.trim()};setText('');try{const r=await fetch(API+'/helpdesk/tickets/'+selected.id+'/messages',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessages(x=>[...x,{id:d.messageId,sender_user_id:user.id,sender_name:user.name||'You',message_text:body.message,sent_at:new Date().toISOString(),is_internal_note:false}]);}catch(e:any){setMsg(e.message||'Message failed.');}};
 return <div className="min-h-screen bg-slate-50 p-6 md:p-10"><div className="max-w-6xl mx-auto"><div className="flex justify-between mb-7"><div><p className="text-sm font-bold text-blue-700">NERSF 24/7 HELP DESK</p><h1 className="text-3xl font-bold">Support & Live Assistance</h1><p className="text-slate-500">Secure conversation with the national support desk.</p></div><button onClick={load} className="border bg-white rounded-lg px-4 flex gap-2"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{msg&&<div className="mb-4 bg-blue-50 border p-3 rounded-lg text-blue-800">{msg}</div>}
 <div className="grid md:grid-cols-3 bg-white border rounded-2xl overflow-hidden min-h-[560px]"><aside className="border-r p-4"><button onClick={()=>setCreating(true)} className="w-full bg-blue-700 text-white rounded-lg py-3 font-bold flex justify-center gap-2"><Plus className="h-4 w-4"/>New Support Request</button><div className="mt-4 space-y-2">{tickets.map(t=><button onClick={()=>open(t)} key={t.id} className={'w-full text-left p-3 rounded-lg border '+(selected?.id===t.id?'bg-blue-50 border-blue-300':'')}><p className="font-bold text-sm truncate">{t.subject}</p><p className="text-xs text-slate-500 mt-1">{t.status} • {t.priority}</p></button>)}{!tickets.length&&<p className="text-sm text-slate-500 p-4">No support requests yet.</p>}</div></aside>
 <main className="md:col-span-2 flex flex-col">{!selected?<div className="flex-1 grid place-items-center text-center text-slate-500"><div><Headphones className="h-12 w-12 mx-auto mb-3 text-blue-600"/><p className="font-bold">Select or create a support request</p><p className="text-sm">Your conversation history is securely retained.</p></div></div>:<><div className="p-5 border-b"><h2 className="font-bold">{selected.subject}</h2><p className="text-xs text-slate-500">{selected.status} • Priority: {selected.priority}</p></div><div className="flex-1 p-5 space-y-3 overflow-auto max-h-[420px]">{messages.map(m=><div key={m.id} className={'max-w-[80%] rounded-2xl p-3 '+(m.sender_user_id===user.id?'ml-auto bg-blue-700 text-white':'bg-slate-100')}><p className="text-xs font-bold opacity-75">{m.sender_name}</p><p>{m.message_text}</p><p className="text-[10px] opacity-70 mt-1">{new Date(m.sent_at).toLocaleTimeString()}</p></div>)}<div ref={bottom}/></div><form onSubmit={send} className="border-t p-4 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type your message..." className="flex-1 border rounded-lg px-4"/><button className="bg-blue-700 text-white p-3 rounded-lg"><Send className="h-5 w-5"/></button></form></>}</main></div>
 {creating&&<div className="fixed inset-0 bg-black/60 grid place-items-center p-4"><form onSubmit={create} className="bg-white w-full max-w-md rounded-2xl p-6"><h2 className="text-xl font-bold">Create Support Request</h2><p className="text-sm text-slate-500 mt-1">Describe what you need help with.</p><input value={subject} onChange={e=>setSubject(e.target.value)} required className="w-full border rounded-lg p-3 mt-5" placeholder="Support request subject"/><div className="flex justify-end gap-2 mt-5"><button type="button" onClick={()=>setCreating(false)} className="border px-4 py-2 rounded-lg">Cancel</button><button className="bg-blue-700 text-white px-4 py-2 rounded-lg">Create</button></div></form></div>}</div></div>;
}