import React,{useEffect,useRef,useState}from'react';
import {io,Socket}from'socket.io-client';
import {Headphones,Send,RefreshCw,CheckCircle2,Clock,Search}from'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api/v1';
const SOCKET=import.meta.env.VITE_SOCKET_URL||'http://localhost:5000';
interface Ticket{id:string;user_id:string;user_name:string;email:string;subject:string;status:string;priority:string;updated_at:string}
interface Msg{id:string;sender_user_id:string;sender_name:string;message_text:string;sent_at:string;is_internal_note:boolean}

export default function HelpDeskConsole(){
 const token=localStorage.getItem('nersf_token')||'';const user=JSON.parse(localStorage.getItem('nersf_user')||'{}');
 const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [text,setText]=useState('');const [status,setStatus]=useState('OPEN');const [search,setSearch]=useState('');const [notice,setNotice]=useState('');
 const socket=useRef<Socket|null>(null);const bottom=useRef<HTMLDivElement>(null);const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
 const load=async()=>{try{const r=await fetch(API+'/helpdesk/tickets',{headers});const d=await r.json();if(!r.ok)throw new Error(d.message);setTickets(d);}catch(e:any){setNotice(e.message||'Unable to load tickets.');}};
 const open=async(t:Ticket)=>{setSelected(t);setStatus(t.status);try{const r=await fetch(API+'/helpdesk/tickets/'+t.id+'/messages',{headers});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessages(d);}catch(e:any){setNotice(e.message||'Unable to load conversation.');}};
 useEffect(()=>{load();socket.current=io(SOCKET,{auth:{token}});return()=>socket.current?.disconnect();},[]);
 useEffect(()=>{if(!selected||!socket.current)return;const room='ticket_'+selected.id;socket.current.emit('join_ticket',selected.id);const handler=(m:Msg)=>setMessages(x=>[...x,m]);socket.current.on('chat_message',handler);return()=>socket.current?.off('chat_message',handler);},[selected]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!text.trim())return;const message=text.trim();setText('');try{const r=await fetch(API+'/helpdesk/tickets/'+selected.id+'/messages',{method:'POST',headers,body:JSON.stringify({message})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessages(x=>[...x,{id:d.messageId,sender_user_id:user.id,sender_name:user.name||'Support Agent',message_text:message,sent_at:new Date().toISOString(),is_internal_note:false}]);}catch(e:any){setNotice(e.message||'Message failed.');}};
 const update=async()=>{if(!selected)return;try{const r=await fetch(API+'/helpdesk/tickets/'+selected.id,{method:'PATCH',headers,body:JSON.stringify({status,priority:selected.priority})});const d=await r.json();if(!r.ok)throw new Error(d.message);setNotice('Ticket updated successfully.');load();setSelected({...selected,status});}catch(e:any){setNotice(e.message||'Update failed.');}};
 const filtered=tickets.filter(t=>(t.subject+' '+t.user_name+' '+t.email).toLowerCase().includes(search.toLowerCase()));
 return <div className="max-w-7xl mx-auto"><div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold">24/7 Help Desk Console</h1><p className="text-sm text-slate-500">Manage live consumer conversations and support tickets.</p></div><button onClick={load} className="border bg-white rounded-lg px-4 py-2 flex gap-2 font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{notice&&<div className="mb-4 bg-blue-50 border border-blue-200 text-blue-800 p-3 rounded-lg">{notice}</div>}
 <div className="grid lg:grid-cols-3 bg-white border rounded-2xl overflow-hidden min-h-[620px]"><aside className="border-r p-4"><div className="relative mb-4"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tickets..." className="w-full border rounded-lg pl-9 p-2.5"/></div><div className="space-y-2">{filtered.map(t=><button onClick={()=>open(t)} key={t.id} className={'w-full text-left p-4 rounded-xl border '+(selected?.id===t.id?'bg-blue-50 border-blue-400':'hover:bg-slate-50')}><div className="flex justify-between gap-2"><p className="font-bold text-sm truncate">{t.subject}</p><span className="text-[10px] font-bold">{t.status}</span></div><p className="text-xs text-slate-500 mt-1">{t.user_name}</p><p className="text-[10px] text-slate-400">{t.email}</p></button>)}{!filtered.length&&<p className="text-sm text-slate-500 p-4">No tickets found.</p>}</div></aside>
 <main className="lg:col-span-2 flex flex-col">{!selected?<div className="flex-1 grid place-items-center text-center text-slate-500"><div><Headphones className="h-12 w-12 mx-auto mb-3 text-blue-600"/><p className="font-bold">Select a support ticket</p><p className="text-sm">Open a conversation to assist a consumer.</p></div></div>:<><div className="p-5 border-b flex justify-between gap-4"><div><h2 className="font-bold">{selected.subject}</h2><p className="text-sm text-slate-500">{selected.user_name} • {selected.email}</p></div><div className="flex gap-2"><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg px-2 text-sm">{['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].map(s=><option key={s}>{s}</option>)}</select><button onClick={update} className="bg-emerald-700 text-white px-3 rounded-lg text-sm font-bold flex gap-1"><CheckCircle2 className="h-4 w-4"/>Save</button></div></div><div className="flex-1 p-5 space-y-3 overflow-auto max-h-[450px]">{messages.map(m=><div key={m.id} className={'max-w-[80%] rounded-2xl p-3 '+(m.sender_user_id===user.id?'ml-auto bg-slate-900 text-white':'bg-slate-100')}><p className="text-xs font-bold opacity-70">{m.sender_name}</p><p>{m.message_text}</p><p className="text-[10px] opacity-60 mt-1">{new Date(m.sent_at).toLocaleTimeString()}</p></div>)}<div ref={bottom}/></div><form onSubmit={send} className="border-t p-4 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} className="flex-1 border rounded-lg px-4" placeholder="Reply to consumer..."/><button className="bg-blue-700 text-white p-3 rounded-lg"><Send className="h-5 w-5"/></button></form></>}</main></div></div>;
}