import React,{useEffect,useMemo,useState}from'react';
import {ShieldCheck,Search,RefreshCw,Download,Database,Activity,AlertTriangle,Eye,X,Clock}from'lucide-react';

interface Log{id:string;user_id:string|null;action:string;entity:string;entity_id:string|null;details:any;ip_address:string|null;created_at:string;full_name?:string;email?:string}
interface Summary{total:number;today:number;topActions:{action:string;count:number}[]}
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api/v1';

const Reports=()=>{
 const token=localStorage.getItem('nersf_token')||'';
 const [logs,setLogs]=useState<Log[]>([]),[summary,setSummary]=useState<Summary|null>(null),[search,setSearch]=useState(''),[action,setAction]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Log|null>(null),[error,setError]=useState('');
 const limit=25;const headers={Authorization:'Bearer '+token};
 const load=async()=>{setLoading(true);setError('');try{const q=new URLSearchParams({page:String(page),limit:String(limit)});if(search)q.set('search',search);if(action)q.set('action',action);const [lr,sr]=await Promise.all([fetch(API+'/audit/logs?'+q,{headers}),fetch(API+'/audit/summary',{headers})]);const ld=await lr.json(),sd=await sr.json();if(!lr.ok)throw new Error(ld.message||'Unable to load audit ledger.');setLogs(ld.data||[]);setTotal(ld.total||0);if(sr.ok)setSummary(sd);}catch(e:any){setError(e.message||'Unable to connect to the audit service.');}finally{setLoading(false);}};
 useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t)},[page,search,action]);
 const actions=useMemo(()=>Array.from(new Set([...logs.map(x=>x.action),...(summary?.topActions||[]).map(x=>x.action)])),[logs,summary]);
 const exportCSV=()=>{const h='Timestamp,Actor,Action,Entity,Entity ID,IP Address\n';const rows=logs.map(x=>[x.created_at,x.full_name||x.email||'System',x.action,x.entity,x.entity_id||'',x.ip_address||''].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([h+rows],{type:'text/csv'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='NERSF_Audit_Ledger.csv';a.click();URL.revokeObjectURL(u);};
 const pages=Math.max(1,Math.ceil(total/limit));return <div className="space-y-6">
 <div className="flex flex-col md:flex-row justify-between gap-4"><div><p className="text-sm font-bold text-blue-700">GOVERNMENT COMPLIANCE</p><h1 className="text-3xl font-bold text-slate-900">Audit & Activity Ledger</h1><p className="text-slate-500">Real system activity from the NERSF audit database.</p></div><div className="flex gap-2"><button onClick={load} className="border bg-white rounded-lg px-4 py-2 flex gap-2 font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button><button onClick={exportCSV} className="bg-slate-900 text-white rounded-lg px-4 py-2 flex gap-2 font-bold"><Download className="h-4 w-4"/>Export</button></div></div>
 <div className="grid md:grid-cols-3 gap-4">{[{label:'Total Audit Events',value:summary?.total??'—',icon:Database},{label:'Events Today',value:summary?.today??'—',icon:Activity},{label:'Current Page Records',value:logs.length,icon:AlertTriangle}].map((k:any)=><div key={k.label} className="bg-white border rounded-xl p-5"><k.icon className="h-5 w-5 text-blue-700 mb-3"/><p className="text-sm text-slate-500">{k.label}</p><p className="text-3xl font-bold">{k.value}</p></div>)}</div>
 {error&&<div className="bg-red-50 border border-red-200 text-red-800 p-4 rounded-xl">{error}</div>}
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Search actor, email, action or entity..." className="w-full border rounded-lg pl-9 p-2.5"/></div><select value={action} onChange={e=>{setPage(1);setAction(e.target.value)}} className="border rounded-lg px-3"><option value="">All actions</option>{actions.map(a=><option key={a}>{a}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4 text-left">Time</th><th className="p-4 text-left">Actor</th><th className="p-4 text-left">Action</th><th className="p-4 text-left">Entity</th><th className="p-4 text-left">IP</th><th className="p-4"></th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-12 text-center text-slate-500">Loading real audit records...</td></tr>:logs.map(l=><tr key={l.id} className="border-t hover:bg-slate-50"><td className="p-4 whitespace-nowrap"><Clock className="inline h-3 w-3 mr-1 text-slate-400"/>{new Date(l.created_at).toLocaleString()}</td><td className="p-4"><p className="font-bold">{l.full_name||'System / Unknown'}</p><p className="text-xs text-slate-400">{l.email||l.user_id||'—'}</p></td><td className="p-4"><span className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs font-bold">{l.action}</span></td><td className="p-4">{l.entity}{l.entity_id&&<span className="text-xs text-slate-400"> • {String(l.entity_id).slice(0,8)}</span>}</td><td className="p-4 font-mono text-xs">{l.ip_address||'—'}</td><td className="p-4"><button onClick={()=>setSelected(l)} className="text-blue-700"><Eye className="h-4 w-4"/></button></td></tr>)}{!loading&&!logs.length&&<tr><td colSpan={6} className="p-12 text-center text-slate-500">No audit records found.</td></tr>}</tbody></table></div>
 <div className="p-4 border-t flex justify-between items-center"><span className="text-sm text-slate-500">Page {page} of {pages} • {total} total records</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="border px-3 py-1.5 rounded disabled:opacity-40">Previous</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="border px-3 py-1.5 rounded disabled:opacity-40">Next</button></div></div></div>
 {selected&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-auto"><div className="p-5 border-b flex justify-between"><div><h2 className="text-xl font-bold">Audit Event Inspector</h2><p className="text-xs text-slate-500">{selected.id}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="p-6 space-y-4"><div className="grid grid-cols-2 gap-3 text-sm"><div><b>Action:</b> {selected.action}</div><div><b>Entity:</b> {selected.entity}</div><div><b>Actor:</b> {selected.full_name||selected.email||'System'}</div><div><b>IP:</b> {selected.ip_address||'—'}</div></div><div><p className="font-bold mb-2">Recorded Metadata</p><pre className="bg-slate-950 text-emerald-400 p-4 rounded-xl text-xs overflow-auto">{JSON.stringify(typeof selected.details==='string'?JSON.parse(selected.details||'{}'):selected.details,null,2)}</pre></div><div className="flex gap-2 text-sm text-emerald-700"><ShieldCheck className="h-5 w-5"/>Audit record loaded from the system ledger.</div></div></div></div>}
 </div>;
};export default Reports;